package detection

import (
	"os"
	"strings"
)

// IsDistuiGenerated checks if a file was generated by distui
// Returns true if file contains the distui generation marker
func IsDistuiGenerated(filePath string) bool {
	data, err := os.ReadFile(filePath)
	if err != nil {
		return false
	}

	content := string(data)

	// Check for distui generation markers
	markers := []string{
		"# Generated by distui",
		"// Generated by distui",
		"/* Generated by distui",
	}

	for _, marker := range markers {
		if strings.Contains(content, marker) {
			return true
		}
	}

	return false
}

// FileExists checks if a file exists at the given path
func FileExists(filePath string) bool {
	_, err := os.Stat(filePath)
	return err == nil
}

// IsCustomConfig returns true if file exists but was NOT generated by distui
func IsCustomConfig(filePath string) bool {
	if !FileExists(filePath) {
		return false
	}
	return !IsDistuiGenerated(filePath)
}
